# Tarea en Intro00

## Presentado por: Eduardo Pérez

### Ejercicio 1: Carga de datos y preprocesamiento

Cargando y visualizando datos:

In [4]:
import pandas as pd

df_raw = pd.read_csv('kumpula-weather-2017.csv')

df_raw.head(10)

,Year,m,d,Time,Time zone,Precipitation amount (mm),Snow depth (cm),Air temperature (degC)
0,2017,1,1,00:00,UTC,-1.0,-1.0,0.6
1,2017,1,2,00:00,UTC,4.4,-1.0,-3.9
2,2017,1,3,00:00,UTC,6.6,7.0,-6.5
3,2017,1,4,00:00,UTC,-1.0,13.0,-12.8
4,2017,1,5,00:00,UTC,-1.0,10.0,-17.8
5,2017,1,6,00:00,UTC,0.3,10.0,-17.8
6,2017,1,7,00:00,UTC,5.3,10.0,-3.8
7,2017,1,8,00:00,UTC,-1.0,12.0,-0.5
8,2017,1,9,00:00,UTC,1.1,12.0,0.5
9,2017,1,10,00:00,UTC,0.3,9.0,1.7

Creación de la función "monthday_to_days" y de un data frame con copia de los datos para verificar que la función está trabajando correctamente.

In [11]:
from datetime import date

df_working = df_raw.copy()
#print(df_working)

def monthday_to_day(month,day):
    start_date = date(2017,1,1)
    current_date = date(2017,int(month),int(day))
    return (current_date - start_date).days + 1

df_working['days'] = df_working.apply(lambda row: monthday_to_day (row['m'],row['d']), axis=1)

df_working.head()

,Year,m,d,Time,Time zone,Precipitation amount (mm),Snow depth (cm),Air temperature (degC),days
0,2017,1,1,00:00,UTC,-1.0,-1.0,0.6,1
1,2017,1,2,00:00,UTC,4.4,-1.0,-3.9,2
2,2017,1,3,00:00,UTC,6.6,7.0,-6.5,3
3,2017,1,4,00:00,UTC,-1.0,13.0,-12.8,4
4,2017,1,5,00:00,UTC,-1.0,10.0,-17.8,5

In [1]:
print("a")

a